### ISSUE TITLE
CaffeParser: Could not parse deploy file

### ISSUE THREAD

**Issue by github2016-yuan** [talebolano/TensorRT-Yolov3#4]
I follow your step and get TensorRT_my.exe in vs2015. But when I use order  in cmd  I run into some error:
TensorRT_my.exe
####### input args#######                                                                                               C=3;                                                                                                                    H=608;                                                                                                                  W=608;                                                                                                                  caffemodel=yolov3_416.caffemodel;                                                                                       calib=;                                                                                                                 cam=0;                                                                                                                  class=80;                                                                                                               classname=coco.name;                                                                                                    display=1;                                                                                                              evallist=;                                                                                                              input=test.jpg;                                                                                                         inputstream=cam;                                                                                                        mode=fp32;                                                                                                              nms=0.450000;                                                                                                           outputs=yolo-det;                                                                                                       prototxt=yolov3_416.prototxt;                                                                                           savefile=result;                                                                                                        saveimg=0;                                                                                                              videofile=sample.mp4;                                                                                                   ####### end args#######                                                                                                 init plugin proto: yolov3_416.prototxt caffemodel: yolov3_416.caffemodel                                                Begin parsing model...                                                                                                  [libprotobuf ERROR E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param".                                                                    ERROR: CaffeParser: Could not parse deploy file                                                                         ERROR: ssd_error_log: Fail to parse 

Win + vs2015 + cuda10.0 + cudnn7.6.5
It seems that I need to install **protobuf** in my system?

**Comment by talebolano** [comment]
Please comment out all the parameters of upsample layer in the prototype file, such as:


layer {
bottom: "layer19-conv"
top: "layer20-upsample"
name: "layer20-upsample"
type: "Upsample"
#upsample_param {
# scale: 2
#}
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"github2016-yuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 下午5:15
收件人:&nbsp;"talebolano/TensorRT-Yolov3"<TensorRT-Yolov3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[talebolano/TensorRT-Yolov3] CaffeParser: Could not parse deploy file (#4)





 
I follow your step and get TensorRT_my.exe in vs2015. But when I use order  in cmd  I run into some error:
 TensorRT_my.exe
 ####### input args#######                                                                                               C=3;                                                                                                                    H=608;                                                                                                                  W=608;                                                                                                                  caffemodel=yolov3_416.caffemodel;                                                                                       calib=;                                                                                                                 cam=0;                                                                                                                  class=80;                                                                                                               classname=coco.name;                                                                                                    display=1;                                                                                                              evallist=;                                                                                                              input=test.jpg;                                                                                                         inputstream=cam;                                                                                                        mode=fp32;                                                                                                              nms=0.450000;                                                                                                           outputs=yolo-det;                                                                                                       prototxt=yolov3_416.prototxt;                                                                                           savefile=result;                                                                                                        saveimg=0;                                                                                                              videofile=sample.mp4;                                                                                                   ####### end args#######                                                                                                 init plugin proto: yolov3_416.prototxt caffemodel: yolov3_416.caffemodel                                                Begin parsing model...                                                                                                  [libprotobuf ERROR E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param".                                                                    ERROR: CaffeParser: Could not parse deploy file                                                                         ERROR: ssd_error_log: Fail to parse
 
Win + vs2015 + cuda10.0 + cudnn7.6.5
 It seems that I need to install protobuf in my system?

**Comment by github2016-yuan** [comment]
> upsample_param

Thanks for replying. I comment out all the parameters of upsample layer in xx.prototxt，actually, there are two places to comment out. Then I run the order but I get another error:
init plugin proto: yolov3_608.prototxt caffemodel: yolov3_608.caffemodel                                                Begin parsing model...                                                                                                
End parsing model...                                                                                                  
can not find output named yolo-det                                                                                    
 Begin building engine..

It occures when parsing the model, something wrong with the yolov3_608.caffemodel?

**Comment by github2016-yuan** [comment]
> &nbsp;Please comment out all the parameters of upsample layer in the prototype file, such as: layer { &nbsp; &nbsp; bottom: "layer19-conv" &nbsp; &nbsp; top: "layer20-upsample" &nbsp; &nbsp; name: "layer20-upsample" &nbsp; &nbsp; type: "Upsample" &nbsp; &nbsp; #upsample_param { &nbsp; &nbsp; # &nbsp; &nbsp;scale: 2 &nbsp; &nbsp; #} }
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"github2016-yuan"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月1日(星期三) 下午5:15 收件人:&nbsp;"talebolano/TensorRT-Yolov3"<TensorRT-Yolov3@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[talebolano/TensorRT-Yolov3] CaffeParser: Could not parse deploy file (#4) I follow your step and get TensorRT_my.exe in vs2015. But when I use order in cmd I run into some error: TensorRT_my.exe ####### input args####### C=3; H=608; W=608; caffemodel=yolov3_416.caffemodel; calib=; cam=0; class=80; classname=coco.name; display=1; evallist=; input=test.jpg; inputstream=cam; mode=fp32; nms=0.450000; outputs=yolo-det; prototxt=yolov3_416.prototxt; savefile=result; saveimg=0; videofile=sample.mp4; ####### end args####### init plugin proto: yolov3_416.prototxt caffemodel: yolov3_416.caffemodel Begin parsing model... [libprotobuf ERROR E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param". ERROR: CaffeParser: Could not parse deploy file ERROR: ssd_error_log: Fail to parse Win + vs2015 + cuda10.0 + cudnn7.6.5 It seems that I need to install protobuf in my system? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

It works after I comment out the params. I use order like this:
**TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=video --videofile=sample.mp4 --classname=coco.names**
It just runs fast in black cmd screen and I get the result display of red screen with some white words form coco.names. It is normal?
I still test image like this:
**TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=image --image=test.jpg --classname=coco.names**
It still runs very fast.
It confuses me and I think I should get the image with som red boxes just like https://github.com/talebolano/TensorRT-Yolov3#example
I believe your greate job is to test the performance of TensorRT and that is what I am very interested in.
Hope to get reply from you again.
Thanks in advance.

**Comment by talebolano** [comment]
This is not normal. Please check configs.h and YoloConfigs.h, make sure that h and w are both 608, delete the generated *.engine file, and retest with the following formula:
TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=video --videofile=sample.mp4 --classname=coco.names --H=608 --W=608




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"github2016-yuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 上午10:31
收件人:&nbsp;"talebolano/TensorRT-Yolov3"<TensorRT-Yolov3@noreply.github.com&gt;;
抄送:&nbsp;"寒蝉凄切"<240447420@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [talebolano/TensorRT-Yolov3] CaffeParser: Could not parse deploy file (#4)





  
&nbsp;Please comment out all the parameters of upsample layer in the prototype file, such as: layer { &nbsp; &nbsp; bottom: "layer19-conv" &nbsp; &nbsp; top: "layer20-upsample" &nbsp; &nbsp; name: "layer20-upsample" &nbsp; &nbsp; type: "Upsample" &nbsp; &nbsp; #upsample_param { &nbsp; &nbsp; # &nbsp; &nbsp;scale: 2 &nbsp; &nbsp; #} }
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"github2016-yuan"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月1日(星期三) 下午5:15 收件人:&nbsp;"talebolano/TensorRT-Yolov3"<TensorRT-Yolov3@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[talebolano/TensorRT-Yolov3] CaffeParser: Could not parse deploy file (#4) I follow your step and get TensorRT_my.exe in vs2015. But when I use order in cmd I run into some error: TensorRT_my.exe ####### input args####### C=3; H=608; W=608; caffemodel=yolov3_416.caffemodel; calib=; cam=0; class=80; classname=coco.name; display=1; evallist=; input=test.jpg; inputstream=cam; mode=fp32; nms=0.450000; outputs=yolo-det; prototxt=yolov3_416.prototxt; savefile=result; saveimg=0; videofile=sample.mp4; ####### end args####### init plugin proto: yolov3_416.prototxt caffemodel: yolov3_416.caffemodel Begin parsing model... [libprotobuf ERROR E:\Perforce\rboissel_devdt_windows\sw\gpgpu\MachineLearning\DIT\dev\nvmake\externals\protobuf\3.0.0\src\google\protobuf\text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param". ERROR: CaffeParser: Could not parse deploy file ERROR: ssd_error_log: Fail to parse Win + vs2015 + cuda10.0 + cudnn7.6.5 It seems that I need to install protobuf in my system? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
It works after I comment out the params. I use order like this:
 TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=video --videofile=sample.mp4 --classname=coco.names
 It just run fast in black cmd screen and I get the result display of red screen with some white words form coco.names. It is normal?
 I still test image like this:
 TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=image --image=test.jpg --classname=coco.names
 It still run very fast.
 It confuses me and I think I should get the image with som red boxes just like https://github.com/talebolano/TensorRT-Yolov3#example
 I believe your greate job is to test the performance of TensorRT and that is what I am very interested in.
 Hope to get reply from you again.
 Thanks in advance.

**Comment by github2016-yuan** [comment]
@talebolano NICE! It finally works at mod fp16 and fp 32. When I run the order at mod int 8, I get error because lack of cal.list. I wonder how to get it or create it myself?

**Comment by talebolano** [comment]
You should prepare more than 100 pictures in a file, write the address of each picture in cal.list




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"github2016-yuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午2:55
收件人:&nbsp;"talebolano/TensorRT-Yolov3"<TensorRT-Yolov3@noreply.github.com&gt;;
抄送:&nbsp;"寒蝉凄切"<240447420@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [talebolano/TensorRT-Yolov3] CaffeParser: Could not parse deploy file (#4)





 
@talebolano NICE! It finally works at mod fp16 and fp 32. When I run the order at mod int 8, I get error because lack of cal.list. I wonder how to get it or create it myself?

**Comment by github2016-yuan** [comment]
Sorry for some delay. I put 116 images in a file called images and put the path of each image in cal.list
images/00f84af0bf5047da.jpg
images/00faadd9350f458e.jpg
images/00face220e455567.jpg
images/00fbf5d41aae7e48.jpg
images/00fe124a798aafc1.jpg

All the images are airplane from open image v4 dataset.
Then I use the order：TensorRT_my.exe --caffemodel=yolov3_608.caffemodel --prototxt=yolov3_608_trt.prototxt --display=1 --inputstream=video --videofile=sample.mp4 --classname=coco.names **--mode=int8 --calib=cal.list**

The output is: find calibration file, loading ... then it works.
But the inference time is about 38ms, almost the same with fp16 mode.
It seems that int8 mode does not reduce inference time and it confuses me a lot that all the 3 modes take almost the same inference time, about 38ms. Something wrong with the images?
What are the special requirements for the **more than 100 images**?

My environment is: Win10 GTX1070 CPU i7-9700K

**Comment by talebolano** [comment]
That's normal. Only a small number of nvidia gpus support int8 mode, such as tesla p40. But the float16 pattern should be better than float32, check that the correct engine file is loaded.



---Original---

**Comment by github2016-yuan** [comment]
OK, really appreciate you on the great work you do and all the replies you offer me. I will keep going on TensorRT.
